EFinal.Web/EFinal.Web/Controllers/EmpresaController.cs
using EFinal.Web.Funcionalidades.AnularEmpresa;
using EFinal.Web.Funcionalidades.EditarEmpresa;
using EFinal.Web.Funcionalidades.ListarEmpresas;
using EFinal.Web.Funcionalidades.RegistrarEmpresa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace EFinal.Web.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        public ActionResult Listar(string filtro)
        {
            filtro = User.Identity.Name;
            using (var listarEmpresas = new ListarEmpresaHandler())
            {
                return View(new FiltrarEmpresasViewModel() { Filtro = filtro, Empresas = listarEmpresas.Ejecutar(filtro) });
            }
        }

        public PartialViewResult FiltrarporUsuario(string filtro)
        {
            using (var listaPermisos = new ListarEmpresaHandler())
            {
                return PartialView("_LstEmpresasEncontradas", listaPermisos.Ejecutar(filtro));
            }
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View(new RegistrarEmpresaViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(RegistrarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            modelo.StrUsuarioDuenio = User.Identity.Name;

            using (var buscarEmpresa = new ObtenerEmpresaHandler())
            {
                if (buscarEmpresa.ExisteEmpresa(modelo.StrRUC) == true)
                {
                    ModelState.AddModelError("", "El RUC YA ESTÁ REGISTRADO");
                    return View(modelo);
                }
            }

            using (var registrarPermiso = new RegistrarEmpresaHandler())
            {
                try
                {
                    registrarPermiso.Ejecutar(modelo);
                    return RedirectToAction("Listar");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }

        [HttpGet]
        public PartialViewResult Editar(string id)
        {
            using (var buscarPermiso = new ObtenerEmpresaHandler())
            {
                return PartialView("_Editar", buscarPermiso.Ejecutar(id));               
            }
        }

        [HttpPost]
        public ActionResult Editar(EditarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);
            using (var actualizarpermiso = new EditarEmpresaHandler())
            {
                try
                {
                    actualizarpermiso.Ejecutar(modelo);
                    return RedirectToAction("Listar");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }


        [HttpGet]
        public PartialViewResult Eliminar(string id)
        {
            using (var buscarPermiso = new ObtenerEmpresaHandler())
            {
                return PartialView("_Eliminar", buscarPermiso.Ejecutar(id));
            }
        }

        [HttpPost]
        public ActionResult EliminarConfirmacion(EditarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);
            using (var actualizarpermiso = new AnularEmpresaHandler())
            {
                try
                {
                    if (actualizarpermiso.ExisteFacturasEmpresa(modelo.StrRUC) == true)
                    {
                        ModelState.AddModelError("", "EXISTEN FACTURAS ASOCIADAS, NO SE PUEDE ELIMINAR");
                        //return RedirectToAction("Listar");
                        return View(modelo);
                    }
                    else
                    { 
                    actualizarpermiso.Ejecutar(modelo.StrRUC);
                    return RedirectToAction("Listar");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }


    }
}

EFinal.Web/EFinal.Web/Controllers/FacturaController.cs
using EFinal.Web.Comun;
using EFinal.Web.Funcionalidades.AnularEmpresa;
using EFinal.Web.Funcionalidades.AnularFactura;
using EFinal.Web.Funcionalidades.EditarFactura;
using EFinal.Web.Funcionalidades.ListarFactura;
using EFinal.Web.Funcionalidades.RegistrarFactura;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EFinal.Web.Controllers
{
    public class FacturaController : Controller
    {
        // GET: Factura
        public ActionResult Listar(string ruc)
        {
            if (ruc == null)
            {
                ruc = User.Identity.Name;            
            }

            using (var listarEmpresas = new ListarFacturaHandler())
            {
                return View(new FiltrarFacturaViewModel() { Filtro = ruc, Facturas = listarEmpresas.Ejecutar(ruc) });
            }
        }

        public PartialViewResult FiltrarporUsuario(string ruc)
        {
            using (var listaPermisos = new ListarFacturaHandler())
            {
                return PartialView("_LstFacturasEncontradas", listaPermisos.Ejecutar(ruc));
            }
        }
      

        [HttpGet]
        public ActionResult Registrar(string ruc)
        {
            RegistrarFacturaViewModel vista = new RegistrarFacturaViewModel();
            vista.StrRUC = ruc;
            return View(vista);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            using (var buscarPermiso = new ObtenerFacturaHandler())
            {
                return View(buscarPermiso.Ejecutar(id));
            }
        }

        [HttpPost]
        public ActionResult Editar(EditarFacturaViewModel modelo, HttpPostedFileBase image)
        {       
            string ruta = Server.MapPath("~/imagenes/Albums");
            if (!ModelState.IsValid) return View(modelo);          
            using (var registrarPermiso = new EditarFacturaHandler())
            {
                try
                {
                    Imagen imagen = ObtenerImagen(image, ruta);
                    registrarPermiso.Ejecutar(modelo, imagen);
                    return RedirectToAction("Listar", new { ruc = modelo.StrRUC });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }


        private Imagen ObtenerImagen(HttpPostedFileBase image, string ruta)
        {
            if (image == null) return null;
            var stream = new MemoryStream();

            image.InputStream.CopyTo(stream);
            return new Imagen(
                stream,
                image.FileName,
                image.ContentType,
                ruta);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(RegistrarFacturaViewModel modelo, HttpPostedFileBase image)
        {
            string ruta = Server.MapPath("~/imagenes/Albums");
            if (!ModelState.IsValid) return View(modelo);

            using (var buscarFactura = new ObtenerFacturaHandler())
            {
                if (buscarFactura.ExisteFacturaSerieNumero(modelo.StrSerie,modelo.StrNumero) == true)
                {
                    ModelState.AddModelError("", "La serie y número ya está registrada");
                    return View(modelo);
                }
            }

            using (var registrarPermiso = new RegistrarFacturaHandler())
            {
                try
                {
                    Imagen imagen = ObtenerImagen(image, ruta);
                    registrarPermiso.Ejecutar(modelo, imagen);
                    return RedirectToAction("Listar",new { ruc =modelo.StrRUC});
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }


        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            using (var buscarPermiso = new AnularFacturaHandler())
            {
                return View(buscarPermiso.ObtenerFacturaAnular(id));
            }
        }

        //[HttpPost]
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {            
            using (var actualizarpermiso = new AnularFacturaHandler())
            {
                try
                {
                    actualizarpermiso.Ejecutar(id);
                    return RedirectToAction("Listar");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return RedirectToAction("Listar");
                }
            }
        }

    }
}

EFinal.Web/EFinal.Web/Views/Factura/Editar.cshtml
@model EFinal.Web.Funcionalidades.EditarFactura.ObtenerFacturaViewModel

@{
    ViewBag.Title = "Editar Factura";
}

<h2>Editar</h2>

@*@using (Html.BeginForm("Registrar", "Factura", FormMethod.Post, new { enctype = "multipart/form-data" }))*@

@using (Html.BeginForm("Editar","Factura", FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ObtenerFacturaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IntIdRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValueFor(model => model.IntIdRegistro)
                @Html.HiddenFor(model => model.IntIdRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IntIdRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrSerie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrSerie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrSerie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrNumero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrNumero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrNumero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtFechaEmision, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtFechaEmision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtFechaEmision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtFechaVcto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtFechaVcto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtFechaVcto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtFechaCobro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtFechaCobro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtFechaCobro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DcTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DcTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DcTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DcImpuesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DcImpuesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DcImpuesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrRUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrRUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrRUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrRSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrRSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrRSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.StrNombreArchivoFactura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrNombreArchivoFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrNombreArchivoFactura, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-10">
                <input type="file" name="image" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Cambios" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listado Facturas", "Listar","Factura")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EFinal.Web/EFinal.Web/Views/Factura/Eliminar.cshtml
@model EFinal.Web.Funcionalidades.AnularFactura.AnularFacturaViewModel

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Desea Eliminar la Factura?</h3>
<div>
    <h4>AnularFacturaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IntIdRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IntIdRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StrSerie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StrSerie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StrNumero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StrNumero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DtFechaEmision)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DtFechaEmision)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DtFechaVcto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DtFechaVcto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DtFechaCobro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DtFechaCobro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DcTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DcTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DcImpuesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DcImpuesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StrRUC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StrRUC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StrRSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StrRSocial)
        </dd>

    </dl>

    @*@using (Html.BeginForm("ConfirmarEliminar", "Factura", FormMethod.Post, new { id = Model.IntIdRegistro }))
    {*@
        @using (Html.BeginForm()) { 
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar al Listado", "Listar","Factura")
        </div>
    }
</div>

EFinal.Web/EFinal.Web/Views/Factura/Listar.cshtml
@model EFinal.Web.Funcionalidades.ListarFactura.FiltrarFacturaViewModel
@{
    ViewBag.Title = "Listado de Facturas por Empresa";
}


@using (Ajax.BeginForm("FiltrarporUsuario", "Factura",
                                                    new AjaxOptions
                                                    {
                                                        HttpMethod = "Get",
                                                        InsertionMode = InsertionMode.Replace,
                                                        UpdateTargetId = "ResultadoFiltro",

                                                    },
                                                    new
                                                    {

                                                        id = "FiltrarEmpresas",
                                                        @class = "form-inline"
                                                    }
                                                    ))
{
    <div class="form-group col-sm-10 col-lg-10 col-xs-10 col-md-10">
        <input type="hidden" placeholder="Buscar por Razón Social."
               name="Filtro" value="@Model.Filtro"
               class="form-control" />
    </div>
    @*<input type="submit" value="Filtrar..." class="btn btn-success" />*@
}


<div id="ResultadoFiltro">
    @if (Model.Facturas.Count() > 0)
    {
        @Html.Partial("_LstFacturasEncontradas", Model.Facturas)
    }
</div>

<div id="EditarEmpresaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EditarEmpresalabel"
     aria-hidden="true">
</div>

<div id="EliminarEmpresaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EliminarEmpresalabel"
     aria-hidden="true">
</div>

<div id="RegistrarEmpresaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="RegistrarEmpresalabel"
     aria-hidden="true">
</div>

@section Scripts{
    @Scripts.Render("~/bundles/unobtrusiveajax")
}

EFinal.Web/EFinal.Web/Views/Factura/Registrar.cshtml
@model EFinal.Web.Funcionalidades.RegistrarFactura.RegistrarFacturaViewModel

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar</h2>
@using (Html.BeginForm("Registrar", "Factura", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@*@using (Html.BeginForm("Registrar", "Factura", FormMethod.Post, new { enctype = "multipart/form-data" }, new
{
    id = "PermisoNuevoForm",
    @class = "form-horizontal",
    role = "form"
}))
{*@
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegistrarFacturaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StrSerie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrSerie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrSerie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrNumero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StrNumero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrNumero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtFechaEmision, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtFechaEmision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtFechaEmision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtFechaVcto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtFechaVcto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtFechaVcto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtFechaCobro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtFechaCobro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtFechaCobro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DcTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DcTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DcTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DcImpuesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DcImpuesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DcImpuesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrRUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValueFor(model => model.StrRUC )
                @Html.ValueFor(model => model.StrRSocial)
                @Html.HiddenFor(model => model.StrRUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StrRUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">            
            <div class="col-md-10">
                <input type="file" name="image" class="form-control" />
            </div>
        </div>


      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Grabar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listado de Empresas","Listar","Empresa")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EFinal.Web/EFinal.Web/Views/Factura/_LstFacturasEncontradas.cshtml
@model IEnumerable<EFinal.Web.Funcionalidades.ListarFactura.ListarFacturaViewModel>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IntIdRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StrSerie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StrNumero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtFechaEmision)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtFechaVcto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtFechaCobro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DcTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DcImpuesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StrRUC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StrRazonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StrNombreArchivoFactura)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IntIdRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StrSerie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StrNumero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtFechaEmision)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtFechaVcto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtFechaCobro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DcTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DcImpuesto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StrRUC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StrRazonSocial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StrNombreArchivoFactura)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new {  id=item.IntIdRegistro  }) |
            @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
            @Html.ActionLink("Eliminar", "Eliminar", new {  id=item.IntIdRegistro })
        </td>
    </tr>
}

</table>